version: "3"
services:
    tradebot:
        image: crypto-tradebot:local
        ports: 
            - "9000:9000"
        environment:
            PORT: "9000"
            GCLOUD_PROJECT: ${gcloudProject}
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro
    schedule-fanout:
        image: schedule-fanout:local
        ports: 
            - "9001:9000"
        environment:
            PORT: "9000"
            GCLOUD_PROJECT: ${gcloudProject}
            TARGET_TOPIC: ${tradebotTopic}
            GOOGLE_APPLICATION_CREDENTIALS: /home/tradebot/.config/gcloud/application_default_credentials.json
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro
    api:
        image: api-service:local
        ports:
            - "9002:9000"
        environment:
            PORT: "9000"
            GCLOUD_PROJECT: ${gcloudProject}
            GOOGLE_APPLICATION_CREDENTIALS: /home/tradebot/.config/gcloud/application_default_credentials.json
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro
    frontend:
        image: coinpilot-fe:local
        depends_on: 
            - api
        ports:
            - "3001:3000"
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /home/tradebot/.config/gcloud/application_default_credentials.json
            HOSTNAME: "0.0.0.0"
            COINBASE_CLIENT_ID: ${cbClientId}
            COINBASE_CLIENT_SECRET: ${cbClientSecret}
            SESSION_SECRET: ${sessSecret}
            NODE_ENV: "development"
            # SERVER_SESSION: "true"
            API_URL: "http://api:9000"
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro

