version: "3"
services:
    tradebot:
        image: crypto-tradebot:local
        ports: 
            - "9000:9000"
        environment:
            PORT: "9000"
            GCLOUD_PROJECT: ${gcloudProject}
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro
    schedule-fanout:
        image: schedule-fanout:local
        ports: 
            - "9001:9000"
        environment:
            PORT: "9000"
            GCLOUD_PROJECT: ${gcloudProject}
            TARGET_TOPIC: ${tradebotTopic}
        volumes:
            - ${localDevHome}/.config/gcloud:/home/tradebot/.config/gcloud:ro
